### ISSUE TITLE
Drop-nth bug

### ISSUE THREAD

**Issue by anovakovic01** [NapredneTehnikeProgramiranja/NapredneTehnikeProgramiranja.github.io#1]
## Vaša primedba je vezana za koji deo kursa?

*Clojure*

## Moja primedba je na:

- [ ] neistinu/nekorektnost u tekstu
- [ ] nepotpunost
- [ ] nejasnoću
- [ ] nedostatak primera
- [x] pogrešan primer
- [ ] grešku u pisanju
- [ ] korišćenje pogrešnog pojma
- [ ] sugestija

## Gde je to?

*http://naprednetehnikeprogramiranja.tk/org/clojure.html#text-3-4*

## Primedba

*Funkcija drop-nth odstrani više elemenata nego što bi trebalo.*

**Comment by novakboskov** [comment]
@Novke01 Jesi na ovo mislio?

Takođe, sada mi se čini smislenije da `drop-nth*` za `(> n (count v))` vraća sekvencu koja je prosleđena (`v`) nego da vraća prazan vektor.

**Comment by anovakovic01** [comment]
@novakboskov Da, na to sam mislio. 

Sada mi izgleda dobro, sa tim da bi možda bilo logičnije da u slučaju ```(> n (count v))``` funkcija vraća sekvencu (```v```) bez 0, pošto se u svim slučajevima 0 izbaci (nula je deljiva bilo kojim prirodnim brojem).

**Comment by novakboskov** [comment]
@Novke01 Misliš prvi element sekvence (element na ideksu 0)?

Ne znam, ja ipak ne bih. Npr. "izbaci svaki 100. element vektora `[11 12 13]`" više bih smatrao besmislenim pozivom i samo bih vratio `[11 12 13]`.
